import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  penetrationSidebar: [{type: 'autogenerated', dirName: 'penetration'}],
  toolsSidebar: [{type: 'autogenerated', dirName: 'tools'}],
  developSidebar: [{type: 'autogenerated', dirName: 'develop'}],
  helpSidebar: [{type: 'autogenerated', dirName: 'help'}],
  blueSidebar: [{type: 'autogenerated', dirName: 'blueteam'}],
  tetralogySidebar: [{type: 'autogenerated', dirName: 'tetralogy'}],
  miscSidebar: [{type: 'autogenerated', dirName: 'misc'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
